// Code generated by "stringer -type=state"; DO NOT EDIT

package j

import "fmt"

const _state_name = "stateBeginJSONstateEndJSONstateBeginObjectstateInObjectstateEndObjectstateBeginMemberstateInMemberstateBeginMemberKeystateEndMemberKeystateInMemberValuestateBeginArraystateInArraystateBeginArrayValuestateEndArraystateBeginStringstateInStringstateEndStringstateInStringEscapestateInStringEscapeUstateInStringEscapeUxstateInStringEscapeUxxstateInStringEscapeUxxxstateInStringEscapeUxxxxstateBeginNumberstateInNumberstateBeginNumberFracstateInNumberFracstateBeginNumberExpstateInNumberExpstateEndNumberstateBeginNullstateInNullstateEndNullstateInFalsestateInTruestateEndBoolstateError"

var _state_index = [...]uint16{0, 14, 26, 42, 55, 69, 85, 98, 117, 134, 152, 167, 179, 199, 212, 228, 241, 255, 274, 294, 315, 337, 360, 384, 400, 413, 433, 450, 469, 485, 499, 513, 524, 536, 548, 559, 571, 581}

func (i state) String() string {
	if i < 0 || i >= state(len(_state_index)-1) {
		return fmt.Sprintf("state(%d)", i)
	}
	return _state_name[_state_index[i]:_state_index[i+1]]
}
