// Code generated by "stringer -type=State"; DO NOT EDIT

package json

import "fmt"

const _State_name = "stateBeginJSONstateEndJSONstateBeginObjectstateInObjectstateBeginMemberstateInMemberstateInMemberKeystateEndMemberKeystateInMemberValuestateBeginArraystateInArraystateArrayValuestateBeginValuestateInStringstateInStringEscapestateInFalsestateInTruestateInNullstateError"

var _State_index = [...]uint16{0, 14, 26, 42, 55, 71, 84, 100, 117, 135, 150, 162, 177, 192, 205, 224, 236, 247, 258, 268}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return fmt.Sprintf("State(%d)", i)
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
