// Code generated by "stringer -type=State"; DO NOT EDIT

package scanner

import "fmt"

const _State_name = "stateBeginJSONstateEndJSONstateBeginObjectstateInObjectstateBeginMemberstateInMemberstateBeginMemberKeystateEndMemberKeystateInMemberValuestateBeginArraystateInArraystateArrayValuestateBeginValuestateInStringstateInStringEscapestateInStringEscapeUstateInStringEscapeUxstateInStringEscapeUxxstateInStringEscapeUxxxstateInStringEscapeUxxxxstateBeginNumberstateInNumberstateBeginNumberFracstateInNumberFracstateBeginNumberExpstateInNumberExpstateInFalsestateInTruestateInNullstateError"

var _State_index = [...]uint16{0, 14, 26, 42, 55, 71, 84, 103, 120, 138, 153, 165, 180, 195, 208, 227, 247, 268, 290, 313, 337, 353, 366, 386, 403, 422, 438, 450, 461, 472, 482}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return fmt.Sprintf("State(%d)", i)
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
